version: '3'
services:
  redis:
    image: redis:7.0
    container_name: redis
    volumes:
      - /home/ubuntu/redis/data:/data:rw
      - /home/ubuntu/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf:rw
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass frM991103@
    networks:
      - my_network
    ports:
      - 6379:6379
    
  chatbot:
    image: chatbot:latest
    container_name: chatbot
    volumes:
      - /home/ubuntu/chatgpt-telegram-bot-py:/chatgpt-telegram-bot-py
    command: python3 main.py
    networks:
      - my_network
    depends_on:
      - redis
    ports:
      - 8080:8080

  app:
    image: chatbot:latest
    container_name: app
    volumes:
      - /home/ubuntu/chatgpt-telegram-bot-py:/chatgpt-telegram-bot-py
    command: python3 app.py
    networks:
      - my_network
    depends_on:
      - redis
      - chatbot
    ports:
      - 8000:8000

  web:
    image: nginx
    container_name: nginx
    volumes:
      - /usr/local/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /usr/local/nginx/conf.d:/etc/nginx/conf.d
      - /usr/local/nginx/ssl:/etc/nginx/ssl
    restart:
      always
    ports:
      - 443:443
      



networks:
  my_network: