version: '3'
services:
  redis:
    image: redis:4.0.1
    container_name: redis-label
    volumes:
      - /redis/datadir:/data
      - /redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /redis/logs:/logs
    command: redis-server --requirepass frM991103
    ports:
      - 6379:6379
    
  chatbot:
    image: chatbot:latest
    container_name: chatbot
    volumes:
      - /chatbot:/app
    depends_on:
      - redis
