version: '3'
services:
  redis:
    image: redis:7.0
    container_name: redis
    volumes:
      - /home/ubuntu/redis/data:/data:rw
      - /home/ubuntu/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf:rw
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - my_network
    ports:
      - 6379:6379
    
  chatbot:
    image: chatbot:latest
    container_name: chatbot
    volumes:
      - /home/ubuntu/chatgpt-telegram-bot-py:/chatgpt-telegram-bot-py
    command: python3 main.py
    networks:
      - my_network
    depends_on:
      - redis

  app:
    image: chatbot:latest
    container_name: app
    volumes:
      - /home/ubuntu/chatgpt-telegram-bot-py:/chatgpt-telegram-bot-py
    command: python3 app.py
    networks:
      - my_network
    depends_on:
      - redis
      - chatbot
    ports:
      - 8000:8000


networks:
  my_network: